name: "generate-breakout-game-from-github-contribution-grid"
description: "Generates a breakout game animation from a github user contributions grid."
author: "cherninlab"

branding:
  icon: "play"
  color: "green"

runs:
  using: "docker"
  image: "docker://ghcr.io/cherninlab/breek@sha256:0e397d9ece4974e3de27fa8af4e5cc54a79661dab0296ca69d7bcdc843d2bb6d"

inputs:
  github_user_name:
    description: "GitHub username"
    required: true
  github_token:
    description: "GitHub token used to fetch the contribution calendar. Defaults to the action token if empty."
    required: false
    default: ${{ github.token }}
  svg_out_path:
    description: "Output path for the light mode SVG file"
    required: true
  svg_dark_out_path:
    description: "Output path for the dark mode SVG file"
    required: true

outputs:
  svg_path:
    description: "Path to the generated light mode SVG file"
  svg_dark_path:
    description: "Path to the generated dark mode SVG file"
